### ISSUE TITLE
[zootr-sim] Closed Deku requires the player to find a Deku Shield.

### ISSUE THREAD

**Issue by Mijati** [scatter-dev/scatter.live#11]
Seed: DO9WURXMIX
Settings: AJCNGKAENSAAZNBAAVLAAAAAEBAASHSWAA

I've tested this with multiple different seeds. Even though a Deku Shield would be available in the Kokiri Shop, you won't be allowed to the Deku Tree Lobby (or to check the hints) until you find a shield somewhere. This could lead to unbeatable seeds.

In the seed above you can find Kokiri sword in Mido's house to quick demonstrate this issue.

**Comment by scatter-dev** [comment]
Fixed. Logic now assumes you have a Deku Shield in the forest unless shops are shuffled.
