### ISSUE TITLE
[zootr-sim] HTTPS Certificate Error

### ISSUE THREAD

**Issue by Nicholas-Steel** [scatter-dev/scatter.live#12]
I get a HTTPS certificate error in Firefox when trying to access the website via http://scatter.live/zootr-sim/

See https://pastebin.com/Q69KQJ0i for a copy of the error.

**Comment by scatter-dev** [comment]
Looks like scatter.live isn't redirecting properly, not sure why. I'll get it sorted out; In the meantime, www.scatter.live works.

**Comment by scatter-dev** [comment]
Fixed.
