### ISSUE TITLE
[zootr-sim] Light arrow hint... in your pocket?

### ISSUE THREAD

**Issue by wakamoleguy** [scatter-dev/scatter.live#13]
![49EBC4CD-97E5-40EE-9B38-70AE3EB8E277](https://user-images.githubusercontent.com/3210372/86535524-f0195380-beae-11ea-8c10-450fb7bc9f75.png)

Light arrows are in my pocket, I guess. In reality, they were in the field. Here’s the play through id:

![3A9A10A2-BAFE-41B8-8331-AFD10391CFCF](https://user-images.githubusercontent.com/3210372/86535754-ae89a800-beb0-11ea-99dd-57811793bed8.png)

Btw, thanks for making an excellent sim!

**Comment by scatter-dev** [comment]
Fixed.
