### ISSUE TITLE
[zootr-sim] bring back the Undo button for non-leaderboard use

### ISSUE THREAD

**Issue by jaredbranum** [scatter-dev/scatter.live#16]
i do a lot of seeds on my phone, and my fat thumb ends up misclicking a lot. could we get the undo button back, even if only when logic isn’t enforced?

**Comment by scatter-dev** [comment]
Sorry, the undo logic is way too complicated, it was already broken when it was in there before and now that I have to worry about client-server stuff it's way worse. The offline version is still on there which is unchanged from the big update, but I don't know if there's a way to run that on mobile. 

(Did we talk about this in discord dms or something? I thought I remembered it but I can't find the convo now.)
