### ISSUE TITLE
[zootr-sim] Easy Mode: Can't get Kokiri Sword from sword chest

### ISSUE THREAD

**Issue by renataskyfire** [scatter-dev/scatter.live#18]
Settings: AJGPGKAESVNAHAAAATCAJELEYEAFAAASFBAASRSWAA (Easy Mode)
Seed: RPVWXUMN96
Playthrough ID: 5f46c5a1a7df4e591a58366d

The Kokiri Sword chest is not available to check:
![image](https://user-images.githubusercontent.com/721484/91354427-5edda380-e7b2-11ea-857a-5007e2614783.png)

I think this means all easy mode seeds are unbeatable unless you get a scale or explosives to leave through the Lost Woods, and other seeds could be as well if there's progression in the sword chest.

**Comment by scatter-dev** [comment]
Sorry this one took so long. Fixed in 6615e83.
