### ISSUE TITLE
[zootr-sim] Restricted access to Zora's river when having one remaining bombchu

### ISSUE THREAD

**Issue by mjbuchman** [scatter-dev/scatter.live#19]
There's an issue with the logic checking for the ability to access river as a child when you have one bombchu and no bomb bag/scale. I was able to go to the river and check the lower freestanding HP which upon clicking, removed my last remaining bombchu. Afterwards, with no remaining explosives I was barred from checking the remaining parts of river. Upon recreating the issue it looks like every time you do a check in river as a child it removes a bombchu from inventory instead of setting a flag for river access after the first check/bombchu used.

**Comment by scatter-dev** [comment]
Fixed in fb11dd2, the sim will now remember opening Zora River as child with chus.
