### ISSUE TITLE
[zootr-sim] Lake Hylia peek icon should be on Sun check

### ISSUE THREAD

**Issue by philting** [scatter-dev/scatter.live#20]
There is currently a peek icon on "Lake Hylia Freestanding PoH." It should be moved to "Lake Hylia Sun."

**Comment by philting** [comment]
<img width="294" alt="Screen Shot 2020-09-14 at 10 36 23 AM" src="https://user-images.githubusercontent.com/1680910/93124008-484bad80-f6c9-11ea-872e-74d0138b2196.png">

**Comment by scatter-dev** [comment]
I'll keep the one on the freestanding heart piece, because theoretically, if you were trying to go for low items, you *could* look at it without picking it up. I did add it to Lake Hylia Sun and made it so you can peek if you have a bow. Fixed in 8eb5695.
