### ISSUE TITLE
[zootr-sim] Recalling Farore's Wind breaks all logic

### ISSUE THREAD

**Issue by philting** [scatter-dev/scatter.live#21]
After recalling to a dungeon with Farore's Wind, the user is unable to click on any of the checks. The only actions available are save-warping and song-warping.

**Comment by philting** [comment]
<img width="895" alt="Screen Shot 2020-09-14 at 11 32 51 AM" src="https://user-images.githubusercontent.com/1680910/93124181-82b54a80-f6c9-11ea-8931-715a2e2dc06e.png">

**Comment by philting** [comment]
Steps to reproduce:

1. Load the following settings string, and Enforce Logic (Scrubs settings + Farore's, Magic, Bombs as 
 starting items): AJEPGBAESZAAHJAAATCAJELEYEAFAACSAE2AE2AETSCAUKWALNBA6EAFAA
2. Go to Deku Tree Lobby
3. Set Wind
4. Get Impa at Castle check (for Zelda's letter)
5. Go to Dodongo's Cavern
6. Recall Wind
7. Click on any check in Deku Tree

**Comment by scatter-dev** [comment]
Sorry I let this one slip by for so long, it's pretty bad. Fixed in 14af88f.
