### ISSUE TITLE
[zootr-sim] Composer grave chest not accessible as child

### ISSUE THREAD

**Issue by philting** [scatter-dev/scatter.live#22]
One of the most common tricks to perform is lighting the torches in composer grave as a child using deku sticks. Technically not in logic, but very commonly done, and I think that it should be added.

**Comment by scatter-dev** [comment]
The paradigm I decided on when adding logic to the sim was, if it was a trick that could be enabled in the randomizer settings, I would allow it in the sim always. If not, it wouldn't be allowed. You do end up missing out on some stuff like this, but rulesets and such are a lot more fluid than the randomizer settings so I feel like it's a bit of a slippery slope, or at least it'd be hard to keep up with.
