### ISSUE TITLE
[zootr-sim] Users should be able to see what is out of logic

### ISSUE THREAD

**Issue by philting** [scatter-dev/scatter.live#24]
When clicking on a check that's out of logic, users just see a cryptic "Can't Access That." Would be nice if it would lay out the items that are missing.

**Comment by philting** [comment]
This is an enhancement request.

**Comment by scatter-dev** [comment]
I think this is too complicated to implement. For example (and it's one of the worst examples, but not the only bad one), the logic for the Gold Skulltula in child side spirit climb:

`has_projectile(both) or can_use(Dins_Fire) or ((damage_multiplier != 'ohko' or Fairy or can_use(Nayrus_Love)) and (Sticks or Kokiri_Sword or has_projectile(child))) or (is_child and (Small_Key_Spirit_Temple, 5) and has_projectile(child)) or (((Small_Key_Spirit_Temple, 3) or ((Small_Key_Spirit_Temple, 2) and bombchus_in_logic and not shuffle_dungeon_entrances)) and can_use(Silver_Gauntlets) and (has_projectile(adult) or damage_multiplier != 'ohko' or Fairy or can_use(Nayrus_Love)))`

Suffice to say it isn't always easy to figure out what's missing, or at least a useful subset of those. Plus I've talked to some people in the community who seem to think that knowing what items you need is part of the challenge/fun, which isn't a reason not to include it at all, but it's at least some justification. But yeah, mainly the logic is just too complicated a lot of the time (and for the easy logic checks, you probably already know what you're missing anyway).
