### ISSUE TITLE
[zootr-sim] Hints system doesn't keep track well

### ISSUE THREAD

**Issue by djluis48** [scatter-dev/scatter.live#29]
Hi!

First of all would like to thanks you because this is an awesome tool for someone who want to get into OoTR and doesnt know logic well, thanks dude! 

I would like to report that i noticed an issue were the hints notes doesn't keep track well of stuff as sometimes when you get a new hint of the same category, ie. way of the hero or foolish, sometimes it deletes one of the previous hints that were already recorded there.

Thanks for your hard work man!

**Comment by scatter-dev** [comment]
Fixed in 50282e2.
