### ISSUE TITLE
[zootr-sim]

### ISSUE THREAD

**Issue by LenKagamine64** [scatter-dev/scatter.live#3]
Shop Sanity doesn't work. Adult shops are not there, as an adult, only child shops.

**Comment by scatter-dev** [comment]
Not seeing this behavior. When I tried, I'm seeing all the shops all the time, regardless of age. Which is still bad, but not nearly as broken. Do you have a seed/settings string/spoiler log?

**Comment by LenKagamine64** [comment]
Here's the string I've been using. AJWYTKAHB2BGAJKWAAASAASFDRJLAA

**Comment by scatter-dev** [comment]
Still can't seem to recreate this on Firefox or Chrome. I'm going to close this unless there's any further information you (or anyone else) can give.
